# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Auto-generated Dockerfile
# Build stage
FROM node:lts-alpine AS builder

# Copy server code
COPY src/everything /app
COPY tsconfig.json /tsconfig.json

WORKDIR /app

# Install dependencies and build
RUN npm install && npm run build

# Production image
FROM node:lts-alpine AS release
WORKDIR /app

# Copy built artifacts
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json

# Install only production dependencies
ENV NODE_ENV=production
RUN npm install --production --ignore-scripts

# Start the MCP server over stdio
CMD ["node", "dist/index.js"]
